# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-21 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beta_invite', '0065_auto_20171221_1617'),
    ]

    state_operations = [
        migrations.CreateModel(
            name='EmailSent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='beta_invite.Campaign')),
                ('email_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='beta_invite.EmailType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='beta_invite.User')),
            ],
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
