# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-21 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing_webpage', '0003_emailsent_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsent',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Candidate'),
        ),
    ]
