# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-21 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing_webpage', '0004_auto_20171221_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='beta_invite.User'),
        ),
    ]
