# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-23 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_remove_state_priority'),
        ('beta_invite', '0065_auto_20171221_1617'),
        ('testing_webpage', '0005_auto_20171221_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=3)),
                ('body_input', models.CharField(max_length=10000)),
                ('subject', models.CharField(max_length=200)),
                ('with_localization', models.BooleanField()),
                ('body_is_filename', models.BooleanField()),
                ('override_dict', picklefield.fields.PickledObjectField(editable=False)),
                ('sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidates', models.ManyToManyField(to='dashboard.Candidate')),
                ('email_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='beta_invite.EmailType')),
            ],
            options={
                'db_table': 'pending_emails',
            },
        ),
        migrations.AlterField(
            model_name='emailsent',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='beta_invite.Campaign'),
        ),
    ]
