# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-10 00:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing_webpage', '0007_auto_20171223_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailsent',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='emailsent',
            name='user',
        ),
    ]
