# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-10 00:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing_webpage', '0008_auto_20180610_0013'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailSent',
            new_name='CandidateEmailSent',
        ),
        migrations.AlterModelTable(
            name='candidateemailsent',
            table='candidate_emails_sent',
        ),
    ]
