# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-10 00:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0107_campaign_work_area'),
        ('business', '0024_auto_20180402_0203'),
        ('testing_webpage', '0009_auto_20180610_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUserEmailSent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='business.BusinessUser')),
                ('email_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='beta_invite.EmailType')),
            ],
            options={
                'db_table': 'business_user_emails_sent',
            },
        ),
    ]
