# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-10 01:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing_webpage', '0010_businessuseremailsent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PendingEmail',
            new_name='CandidatePendingEmail',
        ),
        migrations.AlterModelTable(
            name='candidatependingemail',
            table='candidate_pending_emails',
        ),
    ]
