# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-10 03:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing_webpage', '0012_businessuserpendingemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessuserpendingemail',
            name='email_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='beta_invite.EmailType'),
        ),
    ]
