# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-13 21:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0033_remove_businessuser_added'),
        ('beta_invite', '0180_campaign_added'),
        ('testing_webpage', '0013_auto_20180610_0305'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignEmailSent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='beta_invite.Campaign')),
                ('email_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='beta_invite.EmailType')),
            ],
            options={
                'db_table': 'campaign_emails_sent',
            },
        ),
        migrations.CreateModel(
            name='CampaignPendingEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=3)),
                ('body_input', models.CharField(max_length=10000)),
                ('subject', models.CharField(max_length=200)),
                ('with_localization', models.BooleanField(default=True)),
                ('body_is_filename', models.BooleanField(default=True)),
                ('override_dict', picklefield.fields.PickledObjectField(default={}, editable=False)),
                ('sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaigns', models.ManyToManyField(to='business.BusinessUser')),
                ('email_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='beta_invite.EmailType')),
            ],
            options={
                'db_table': 'campaign_pending_emails',
            },
        ),
    ]
