# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-13 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_webpage', '0014_campaignemailsent_campaignpendingemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignpendingemail',
            name='campaigns',
            field=models.ManyToManyField(to='beta_invite.Campaign'),
        ),
    ]
