# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-10 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing_webpage', '0015_auto_20181213_2128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessuseremailsent',
            old_name='business_user',
            new_name='an_object',
        ),
        migrations.RenameField(
            model_name='campaignemailsent',
            old_name='campaign',
            new_name='an_object',
        ),
        migrations.RenameField(
            model_name='candidateemailsent',
            old_name='candidate',
            new_name='an_object',
        ),
    ]
