# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-10 16:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing_webpage', '0016_auto_20190110_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessuserpendingemail',
            old_name='business_users',
            new_name='the_objects',
        ),
        migrations.RenameField(
            model_name='campaignpendingemail',
            old_name='campaigns',
            new_name='the_objects',
        ),
        migrations.RenameField(
            model_name='candidatependingemail',
            old_name='candidates',
            new_name='the_objects',
        ),
    ]
