# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-10 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_webpage', '0017_auto_20190110_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessuserpendingemail',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaignpendingemail',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidatependingemail',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
