# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 04:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0002_auto_20170625_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profession_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beta_invite.Profession'),
        ),
    ]
