# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 04:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0003_user_profession_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profession_id',
            new_name='profession',
        ),
    ]
