# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 04:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0005_auto_20170625_0429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='country',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='educationlevel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='educationlevel',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='profession',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='profession',
            name='updated_at',
        ),
    ]
