# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0008_profession_name_es'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationlevel',
            name='name_es',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
