# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0010_user_curriculum_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='curriculum_url',
            field=models.CharField(default='#', max_length=200),
        ),
    ]
