# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 16:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0011_auto_20170628_2058'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EducationLevel',
            new_name='Education',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='education_level',
            new_name='education',
        ),
        migrations.AlterModelTable(
            name='education',
            table='education',
        ),
    ]
