# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-24 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0016_auto_20170823_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='description_es',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
