# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-26 00:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0018_trade'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=40, null=True)),
                ('is_mobile', models.NullBooleanField()),
                ('ip', models.GenericIPAddressField(null=True)),
                ('ui_version', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beta_invite.Campaign')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beta_invite.Country')),
                ('trade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beta_invite.Trade')),
            ],
            options={
                'db_table': 'trade_users',
            },
        ),
    ]
