# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-26 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0019_tradeuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeuser',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
