# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-07 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0021_auto_20170905_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignbullet',
            name='campaign',
        ),
    ]
