# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-07 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0022_remove_campaignbullet_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='bullets',
            field=models.ManyToManyField(to='beta_invite.CampaignBullet'),
        ),
    ]
