# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-07 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0023_campaign_bullets'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CampaignBullet',
            new_name='Bullet',
        ),
        migrations.AlterModelTable(
            name='bullet',
            table='bullets',
        ),
    ]
