# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-07 17:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0024_auto_20170907_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bullet',
            old_name='type',
            new_name='bullet_type',
        ),
    ]
