# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-13 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0025_auto_20170907_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='is_mobile',
            field=models.NullBooleanField(),
        ),
    ]
