# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-20 22:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0027_auto_20170920_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiontype',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='questiontype',
            name='updated_at',
        ),
    ]
