# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-20 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0029_auto_20170920_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='name_es',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answers',
            field=models.ManyToManyField(related_name='correct_answers', to='beta_invite.Answer'),
        ),
        migrations.AddField(
            model_name='question',
            name='text_es',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='questiontype',
            name='name_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='name_es',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
