# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-21 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0030_auto_20170920_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='cut_score_percentage',
            field=models.IntegerField(null=True),
        ),
    ]
