# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-21 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0031_test_cut_score_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='cut_score_percentage',
            field=models.IntegerField(default=70),
        ),
    ]
