# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-22 05:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0034_auto_20170922_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beta_invite.User'),
        ),
    ]
