# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-26 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0038_auto_20170926_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluation',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='evaluations',
            field=models.ManyToManyField(null=True, to='beta_invite.Evaluation'),
        ),
    ]
