# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-24 16:59
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0041_question_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalityTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'personality_types',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='additional_params',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
