# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-24 17:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0042_auto_20171024_1659'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonalityTypes',
            new_name='PersonalityType',
        ),
    ]
