# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-24 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0043_auto_20171024_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalitytype',
            name='code',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='personalitytype',
            name='opposite',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
