# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-24 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0044_auto_20171024_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalitytype',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='personalitytype',
            name='updated_at',
        ),
    ]
