# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-26 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0046_auto_20171025_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='numeric_answer',
            field=models.FloatField(null=True),
        ),
    ]
