# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-02 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0047_survey_numeric_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_es', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'interviews',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='video_token',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='video_questions',
            field=models.ManyToManyField(to='beta_invite.Question'),
        ),
    ]
