# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-02 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0048_auto_20171102_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='interviews',
            field=models.ManyToManyField(to='beta_invite.Interview'),
        ),
    ]
