# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-02 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0049_campaign_interviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview',
            old_name='video_questions',
            new_name='questions',
        ),
    ]
