# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-02 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0050_auto_20171102_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
