# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-11 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0057_campaign_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language_code',
            field=models.CharField(default='es', max_length=3),
        ),
    ]
