# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-15 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0059_auto_20171212_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='evaluations',
            field=models.ManyToManyField(to='beta_invite.Evaluation'),
        ),
    ]
