# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-19 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0060_auto_20171215_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='calendly_url',
            field=models.CharField(default='https://calendly.com/santiago-10/llamada-inicial', max_length=200),
        ),
    ]
