# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-21 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0062_auto_20171221_1530'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='emailsent',
            table=None,
        ),
    ]
