# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-21 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0063_auto_20171221_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsent',
            name='email_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='beta_invite.EmailType'),
        ),
    ]
