# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-24 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0069_auto_20180117_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
