# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-02 03:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0071_survey_test_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='test_score',
        ),
    ]
