# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-09 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0075_auto_20180207_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
