# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-13 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0078_evaluation_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='free_trial',
            field=models.BooleanField(default=True),
        ),
    ]
