# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-20 02:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0079_campaign_free_trial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobFunctions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'job_functions',
            },
        ),
        migrations.CreateModel(
            name='Seniority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'seniorities',
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='job_function',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beta_invite.JobFunctions'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='seniority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beta_invite.Seniority'),
        ),
    ]
