# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-07 00:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0080_auto_20180220_0247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradeuser',
            name='ui_version',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ui_version',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='ui_version',
        ),
    ]
