# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-10 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0081_auto_20180307_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='with_email_in_form',
            field=models.BooleanField(default=True),
        ),
    ]
