# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-10 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0083_auto_20180310_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='has_email_in_form',
            new_name='has_email',
        ),
    ]
