# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-11 01:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0085_auto_20180310_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradeuser',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='tradeuser',
            name='country',
        ),
        migrations.RemoveField(
            model_name='tradeuser',
            name='trade',
        ),
        migrations.DeleteModel(
            name='Trade',
        ),
        migrations.DeleteModel(
            name='TradeUser',
        ),
    ]
