# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-17 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0086_auto_20180311_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='ISO',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
