# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-05 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0094_auto_20180405_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='brochure_url',
            field=models.CharField(default='#', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='photo_url',
            field=models.CharField(default='#', max_length=200),
        ),
    ]
