# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-10 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0096_auto_20180409_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.AddField(
            model_name='user',
            name='bdate',
            field=models.DateField(null=True),
        ),
    ]
