# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-10 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0097_auto_20180410_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='politics',
            field=models.BooleanField(default=False),
        ),
    ]
