# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-20 02:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0099_auto_20180413_0147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='dreamjob',
            new_name='dream_job',
        ),
    ]
