# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-20 02:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0100_auto_20180420_0217'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Area',
            new_name='WorkArea',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='hood',
            new_name='neighborhood',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='area',
            new_name='work_area',
        ),
        migrations.AlterModelTable(
            name='workarea',
            table='work_areas',
        ),
    ]
