# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-27 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0101_auto_20180420_0243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='answer',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
