# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-14 03:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0103_auto_20180507_0100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['pk']},
        ),
    ]
