# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-09 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0103_auto_20180507_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
