# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-08 03:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0106_auto_20180517_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='work_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beta_invite.WorkArea'),
        ),
    ]
