# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-10 21:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0107_campaign_work_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='aspiration',
            new_name='salary',
        ),
    ]
