# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-20 00:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0110_auto_20180620_0047'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='workareatype',
            table='work_area_types',
        ),
    ]
