# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-23 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0112_auto_20180620_0258'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_es', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'test_types',
            },
        ),
        migrations.AddField(
            model_name='test',
            name='type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='beta_invite.TestType'),
        ),
    ]
