# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-24 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0113_auto_20180623_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='cognitive_score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='requirements_score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='soft_skills_score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='technical_score',
            field=models.FloatField(null=True),
        ),
    ]
