# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-24 22:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0116_auto_20180624_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='applicant_evaluation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicant_evaluation', to='beta_invite.EvaluationSummary'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='recommended_evaluation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommended_evaluation', to='beta_invite.EvaluationSummary'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='rejected_evaluation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rejected_evaluation', to='beta_invite.EvaluationSummary'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='relevant_evaluation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relevant_evaluation', to='beta_invite.EvaluationSummary'),
        ),
    ]
