# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-26 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0117_auto_20180624_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='curriculm_text',
            field=models.CharField(default='', max_length=100000),
        ),
    ]
