# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-26 03:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0118_user_curriculm_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='curriculm_text',
            new_name='curriculum_text',
        ),
    ]
