# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-26 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0119_auto_20180626_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='curriculum_text',
            field=models.TextField(default=''),
        ),
    ]
