# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-06 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0122_test_feedback_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='passed',
            field=models.NullBooleanField(),
        ),
    ]
