# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-06 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0123_score_passed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='feedback_url',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
