# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-07 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0124_auto_20180706_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='excluding',
            field=models.BooleanField(default=False),
        ),
    ]
