# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-10 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0125_test_excluding'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='try_number',
            field=models.IntegerField(default=1),
        ),
    ]
