# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-28 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0126_auto_20180710_2232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluation',
            old_name='soft_skills_score',
            new_name='motivation',
        ),
        migrations.RenameField(
            model_name='evaluationsummary',
            old_name='soft_skills_score',
            new_name='motivation',
        ),
        migrations.AddField(
            model_name='evaluation',
            name='cultural_fit',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='evaluationsummary',
            name='cultural_fit',
            field=models.FloatField(null=True),
        ),
    ]
