# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-27 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0126_auto_20180710_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='image',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
