# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-28 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0127_auto_20180728_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluation',
            old_name='cultural_fit',
            new_name='cultural_fit_score',
        ),
        migrations.RenameField(
            model_name='evaluation',
            old_name='motivation',
            new_name='motivation_score',
        ),
    ]
