# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-01 02:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0128_auto_20180727_1342'),
        ('beta_invite', '0129_auto_20180729_0007'),
    ]

    operations = [
    ]
