# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-15 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0131_question_importance'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='valid_answer_count',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='text_es',
            field=models.CharField(max_length=1500, null=True),
        ),
    ]
