# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-26 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0133_auto_20180823_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='salary_high_range',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='salary_low_range',
            field=models.IntegerField(null=True),
        ),
    ]
