# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-28 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0134_auto_20180826_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='internal_name',
            field=models.CharField(max_length=1500, null=True),
        ),
    ]
