# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-11 02:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0136_test_is_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='is_public',
            new_name='public',
        ),
    ]
