# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-15 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0139_auto_20180915_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='curriculum_text',
            field=models.TextField(default=None, null=True),
        ),
    ]
