# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-21 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0140_auto_20180915_0325'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkAreaSegment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_es', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'work_area_segments',
            },
        ),
        migrations.RemoveField(
            model_name='workarea',
            name='type',
        ),
        migrations.DeleteModel(
            name='WorkAreaType',
        ),
        migrations.AddField(
            model_name='workareasegment',
            name='work_areas',
            field=models.ManyToManyField(to='beta_invite.WorkArea'),
        ),
    ]
