# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-21 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0141_auto_20180921_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='workareasegment',
            name='code',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
