# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-21 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0142_workareasegment_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workareasegment',
            name='work_areas',
        ),
        migrations.AddField(
            model_name='workarea',
            name='segment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beta_invite.WorkAreaSegment'),
        ),
    ]
