# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-24 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0143_auto_20180921_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='workarea',
            name='code',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
