# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-27 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0145_requirementbinaryquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='free_trial',
            field=models.BooleanField(default=False),
        ),
    ]
