# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-29 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0146_auto_20180927_0121'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True)),
                ('name_es', models.CharField(max_length=40, null=True)),
            ],
            options={
                'db_table': 'campaign_states',
            },
        ),
    ]
