# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-30 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0147_campaignstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignstate',
            name='code',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
