# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-01 02:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0148_campaignstate_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='beta_invite.CampaignState'),
        ),
    ]
