# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-03 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0149_campaign_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='free_trial',
            field=models.BooleanField(default=True),
        ),
    ]
