# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-04 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0150_auto_20181003_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='active',
        ),
    ]
