# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-13 04:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0151_remove_campaign_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beta_invite.WorkArea')),
            ],
            options={
                'db_table': 'requirements',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='uploaded_to_es',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='state',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='beta_invite.CampaignState'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='requirements',
            field=models.ManyToManyField(to='beta_invite.Requirement'),
        ),
    ]
