# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-13 14:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0152_auto_20181013_0430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='user',
            name='evaluations',
        ),
    ]
