# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-18 02:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0153_auto_20181013_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_salary', models.IntegerField()),
                ('to_salary', models.IntegerField()),
                ('price', models.IntegerField()),
                ('work_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beta_invite.WorkArea')),
            ],
            options={
                'db_table': 'prices',
            },
        ),
    ]
