# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-20 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0154_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtype',
            name='code',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
