# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-28 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0155_testtype_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('after_cap_filter', models.ManyToManyField(related_name='cap_search_log', to='beta_invite.User')),
                ('after_city_filter', models.ManyToManyField(related_name='city_search_log', to='beta_invite.User')),
                ('after_duplicates_filter', models.ManyToManyField(related_name='duplicates_search_log', to='beta_invite.User')),
                ('after_recommended_filter', models.ManyToManyField(related_name='recommended_search_log', to='beta_invite.User')),
                ('after_salary_filter', models.ManyToManyField(related_name='salary_search_log', to='beta_invite.User')),
                ('after_work_area_filter', models.ManyToManyField(related_name='work_area_search_log', to='beta_invite.User')),
                ('all_users', models.ManyToManyField(related_name='all_search_log', to='beta_invite.User')),
                ('campaign', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='beta_invite.Campaign')),
                ('users_from_es', models.ManyToManyField(related_name='es_search_log', to='beta_invite.User')),
                ('users_from_search', models.ManyToManyField(related_name='search_search_log', to='beta_invite.User')),
                ('users_from_tests', models.ManyToManyField(related_name='tests_search_log', to='beta_invite.User')),
            ],
            options={
                'db_table': 'search_logs',
            },
        ),
    ]
