# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-28 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0156_searchlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_token',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
