# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-18 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0159_user_auth_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='scores',
            field=models.ManyToManyField(to='beta_invite.Score'),
        ),
    ]
