# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-26 23:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0030_auto_20181008_1828'),
        ('beta_invite', '0161_testtype_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=40)),
                ('highlight', models.CharField(max_length=140)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Company')),
            ],
            options={
                'db_table': 'experiences',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='experiences',
            field=models.ManyToManyField(to='beta_invite.Experience'),
        ),
    ]
