# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-26 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0162_auto_20181126_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='number_of_moths',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='number_of_years',
            field=models.IntegerField(null=True),
        ),
    ]
