# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-26 23:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0163_auto_20181126_2329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='number_of_moths',
            new_name='number_of_months',
        ),
    ]
