# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-26 23:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0031_school'),
        ('beta_invite', '0164_auto_20181126_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('highlight', models.CharField(max_length=140)),
                ('number_of_months', models.IntegerField(null=True)),
                ('number_of_years', models.IntegerField(null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.School')),
            ],
            options={
                'db_table': 'education_experiences',
            },
        ),
    ]
