# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-26 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0165_educationexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='education_experiences',
            field=models.ManyToManyField(to='beta_invite.EducationExperience'),
        ),
    ]
