# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-28 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0167_question_audio_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='audio_url',
        ),
        migrations.AddField(
            model_name='survey',
            name='audio_url',
            field=models.CharField(default='#', max_length=200),
        ),
    ]
