# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-30 18:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0168_auto_20181128_0508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationexperience',
            name='number_of_months',
        ),
        migrations.RemoveField(
            model_name='educationexperience',
            name='number_of_years',
        ),
    ]
