# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-30 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0169_auto_20181130_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
