# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-30 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0170_experience_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='start_year',
            field=models.IntegerField(null=True),
        ),
    ]
