# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-04 20:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0172_user_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationexperience',
            name='highlight',
        ),
    ]
