# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-06 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0173_remove_educationexperience_highlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationexperience',
            name='profession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beta_invite.Profession'),
        ),
    ]
