# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-06 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0174_educationexperience_profession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationexperience',
            name='title',
        ),
        migrations.AddField(
            model_name='educationexperience',
            name='education',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beta_invite.Education'),
        ),
        migrations.AddField(
            model_name='educationexperience',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
