# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-13 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0175_auto_20181206_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=10000)),
                ('contact_name', models.CharField(default='', max_length=200)),
                ('sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'campaign_messages',
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='added',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaignmessage',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beta_invite.Campaign'),
        ),
    ]
