# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-11 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0175_auto_20181206_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
