# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-12 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0176_campaign_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='highlight',
            field=models.CharField(max_length=300),
        ),
    ]
