# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-14 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0177_auto_20181211_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='number_of_months',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='number_of_years',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='start_year',
        ),
        migrations.AddField(
            model_name='experience',
            name='finish_date',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='start_date',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
