# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-13 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0176_auto_20181213_1625'),
        ('beta_invite', '0177_auto_20181211_1931'),
    ]

    operations = [
    ]
