# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-13 19:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0178_merge_20181213_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='added',
        ),
    ]
