# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-14 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0180_campaign_added'),
        ('beta_invite', '0178_auto_20181213_1957'),
    ]

    operations = [
    ]
