# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-14 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0181_merge_20181214_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='finish_date',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='start_date',
        ),
        migrations.AddField(
            model_name='experience',
            name='finish',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experience',
            name='start',
            field=models.DateField(null=True),
        ),
    ]
