UI_VERSION = "1.1.1 - changes name placeholder to 'Your Complete Name'"
BETA_INVITE_VIEW_PATH = 'beta_invite/index.html'
SUCCESS_VIEW_PATH = 'beta_invite/applied.html'
LONG_FORM_VIEW_PATH = 'beta_invite/long_form.html'
FAST_JOB_VIEW_PATH = 'beta_invite/fast_job.html'
HOME_VIEW_PATH = 'beta_invite/home.html'
INTERVIEW_VIEW_PATH = 'beta_invite/interview.html'
DEFAULT_CAMPAIGN_ID = 5
INTERVIEW_CALENDLY = 'https://calendly.com/santiago-10/llamada-inicial'
