# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-24 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_lead_leadmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadmessage',
            name='added',
        ),
        migrations.AddField(
            model_name='lead',
            name='added',
            field=models.BooleanField(default=False),
        ),
    ]
