# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-20 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180924_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='facebook_url',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
