# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-13 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20170913_0458'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CandidateState',
            new_name='Candidate',
        ),
    ]
