# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-13 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20170913_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='comment',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
