# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-13 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_candidate_comment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='candidate',
            table='candidates',
        ),
    ]
