# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-14 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20170913_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='comment',
            field=models.CharField(default='', max_length=10000, null=True),
        ),
    ]
