# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-14 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20170914_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
