# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-14 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_state_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
