# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-15 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20170915_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
