# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-28 23:27
from __future__ import unicode_literals

from django.db import migrations


def migrate_comments(apps, schema_editor):
    # We can't import the Candidate model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    candidate_class = apps.get_model('dashboard', 'Candidate')
    comment_class = apps.get_model('dashboard', 'Comment')

    for candidate in candidate_class.objects.all():
        comment = comment_class(text=candidate.comment)
        comment.save()
        candidate.comments.add(comment)

        # removes value of old comment.
        candidate.comment = ''
        candidate.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20170928_1950'),
    ]

    operations = [
        migrations.RunPython(migrate_comments),
    ]
