# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-29 00:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20170928_2357'),
        ('dashboard', '0015_auto_20170928_2327'),
    ]

    operations = [
    ]
