# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-21 02:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_merge_20170929_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='comment',
        ),
    ]
