# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-21 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0061_campaign_calendly_url'),
        ('dashboard', '0018_remove_candidate_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='evaluations',
            field=models.ManyToManyField(to='beta_invite.Evaluation'),
        ),
    ]
