# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-23 02:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_candidate_evaluations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='priority',
        ),
    ]
