# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-27 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0065_auto_20171221_1617'),
        ('dashboard', '0020_remove_state_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='surveys',
            field=models.ManyToManyField(to='beta_invite.Survey'),
        ),
    ]
