# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-09 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_auto_20180109_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='contact_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
