# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-05 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0072_remove_survey_test_score'),
        ('dashboard', '0024_message_contact_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='scores',
            field=models.ManyToManyField(to='beta_invite.Score'),
        ),
    ]
