# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-13 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_candidate_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='match',
            field=models.FloatField(default=None, null=True),
        ),
    ]
