# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-24 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_candidate_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('passed', models.BooleanField()),
            ],
            options={
                'db_table': 'screening',
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='screening',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Screening'),
        ),
    ]
