# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-24 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_auto_20180224_2039'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='screening',
            table='screenings',
        ),
    ]
