# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-24 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_auto_20180224_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='explanation',
            field=models.CharField(default='', max_length=200),
        ),
    ]
