# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-04 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_auto_20180224_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='honey',
            field=models.IntegerField(default=0),
        ),
    ]
