# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-23 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_state_honey'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
