# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-01 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_candidate_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='match',
            new_name='match_regression',
        ),
        migrations.AddField(
            model_name='candidate',
            name='match_classification',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
