# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-24 04:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_auto_20180401_0239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='honey',
        ),
    ]
