# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-24 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0116_auto_20180624_2028'),
        ('dashboard', '0038_remove_state_honey'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_es', models.CharField(max_length=200)),
                ('candidates', models.ManyToManyField(to='dashboard.Candidate')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beta_invite.Evaluation')),
                ('states', models.ManyToManyField(to='dashboard.State')),
            ],
            options={
                'db_table': 'business_states',
            },
        ),
    ]
