# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-25 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0117_auto_20180624_2228'),
        ('dashboard', '0041_auto_20180624_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='mean_scores',
            field=models.ManyToManyField(null=True, to='beta_invite.Score'),
        ),
    ]
