# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-06 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_candidate_mean_scores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='mean_scores',
            field=models.ManyToManyField(to='beta_invite.Score'),
        ),
    ]
