# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-19 18:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_auto_20180717_0212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='match_regression',
        ),
    ]
