# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-24 04:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0045_remove_candidate_match_regression'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automatic', models.BooleanField(default=False)),
                ('place', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('from_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_state', to='dashboard.State')),
                ('to_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_state', to='dashboard.State')),
            ],
            options={
                'db_table': 'state_events',
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='state_events',
            field=models.ManyToManyField(to='dashboard.StateEvent'),
        ),
    ]
