# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-25 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0046_auto_20180824_0430'),
    ]

    operations = [
        migrations.AddField(
            model_name='stateevent',
            name='ml_criteria',
            field=models.NullBooleanField(default=None),
        ),
    ]
