# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-25 05:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0047_stateevent_ml_criteria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stateevent',
            old_name='ml_criteria',
            new_name='forecast',
        ),
    ]
