# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-27 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0048_auto_20180825_0522'),
    ]

    operations = [
        migrations.AddField(
            model_name='stateevent',
            name='use_machine_learning',
            field=models.BooleanField(default=False),
        ),
    ]
