# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-22 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0050_message_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='sent_to_client',
            field=models.BooleanField(default=False),
        ),
    ]
