# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-07 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0051_candidate_sent_to_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='change_by_client',
            field=models.BooleanField(default=False),
        ),
    ]
