# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-12 22:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0053_candidate_liked'),
        ('dashboard', '0052_candidate_last_evaluation'),
    ]

    operations = [
    ]
