# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-15 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0054_merge_20181212_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='render_cv',
            field=models.BooleanField(default=False),
        ),
    ]
