# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-17 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0054_merge_20181212_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='reason_for_rejection',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
