# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-17 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0055_candidate_render_cv'),
        ('dashboard', '0055_candidate_reason_for_rejection'),
    ]

    operations = [
    ]
