# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 16:47
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0013_user_is_mobile'),
        ('business', '0006_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='education',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beta_invite.Education'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='business_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business.User'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beta_invite.Country'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='experience',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='profession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beta_invite.Profession'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='skills',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
