# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 16:51
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_auto_20170726_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='user_ids',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
