# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-18 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='explanation',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='explanation_es',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='name_es',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
