# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-05 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_auto_20170818_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='applicants',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='plan',
            name='candidates',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='plan',
            name='contract_warranty',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='contract_warranty_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='interview_value',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='interview_value_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='time_in_days',
            field=models.IntegerField(default=10),
        ),
    ]
