# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-05 16:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_auto_20171205_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='interview_value',
            new_name='interview_price',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='interview_value_es',
            new_name='interview_price_es',
        ),
    ]
