# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-15 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_auto_20171205_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='business_user',
            field=models.IntegerField(null=True),
        ),
    ]
