# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-15 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta_invite', '0060_auto_20171215_0058'),
        ('business', '0016_auto_20171215_0445'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessuser',
            name='campaigns',
            field=models.ManyToManyField(to='beta_invite.Campaign'),
        ),
    ]
