# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-05 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0020_auto_20180220_0249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='skills',
        ),
        migrations.AddField(
            model_name='search',
            name='text',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
