# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-07 00:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0021_auto_20180305_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessuser',
            name='ui_version',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='ui_version',
        ),
    ]
