# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-02 02:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0023_auto_20180401_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='businessuser',
            name='country',
        ),
    ]
