# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-10 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0024_auto_20180402_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessuser',
            name='additional_email',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
