# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-04 00:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0027_keyword_work_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='frequency',
        ),
    ]
