# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-04 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0028_remove_keyword_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
