# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-13 19:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0032_businessuser_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessuser',
            name='added',
        ),
    ]
